In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [4]:
# Check weather you are using GPU
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available")

GPU is available
Using GPU:Tesla T4


# **Tensors**

In [8]:
# Allocates memory without any value
a = torch.empty(3,3)
print(f"Type: {type(a)}")
print(a)

Type: <class 'torch.Tensor'>
tensor([[ 1.8603e+07,  4.5352e-41, -8.7832e-24],
        [ 3.2800e-41,  5.9618e+20,  4.5350e-41],
        [ 1.2388e+07,  4.5352e-41, -8.5687e+27]])


In [11]:
zeroes = torch.zeros(2,3)
print(zeroes)
ones = torch.ones(3,3)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
# Rand :- Gives random tensors
torch.rand(1,2)

tensor([[0.7162, 0.6035]])

But every time rand gives different values, if any one want to use this notebook the tensors may be different from yours. So we use function called manual_seed

In [14]:
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [15]:
# tensor:- create custom tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# arange
print(f"Aragnge: {torch.arange(0,10,2)}")
print('*'*50)
# linspace
print(f"LinSpace: {torch.linspace(0,10,6)}")
print('*'*50)

# full
print(f"Full:{torch.full((3,5),10)}")
print('*'*50)

# eye -> Identity matrix (diagonals are 1's)
print(f"Eye:{torch.eye(5)}")
print('*'*50)


Aragnge: tensor([0, 2, 4, 6, 8])
**************************************************
LinSpace: tensor([ 0.,  2.,  4.,  6.,  8., 10.])
**************************************************
Full:tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])
**************************************************
Eye:tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
**************************************************


In [24]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
x.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [38]:
# _like -> Creates Same dimentions of x but different values
print(torch.empty_like(x))
print(torch.zeros_like(x))
print(torch.ones_like(x))
print(torch.rand_like(x,dtype=torch.float32))

tensor([[139002321569160, 100534883871184, 100532299498611],
        [100534882830192,     68719478152, 100534883871216]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.3624, 0.4621, 0.7145],
        [0.5058, 0.0518, 0.2492]])


# **Tensor Data Types**

In [29]:
# find datatype
x.dtype

torch.int64

In [31]:
# assign datatypes
print("Int",torch.tensor([1.0,2.0,3.0],dtype=torch.int32))
print("Float",torch.tensor([1,2,3],dtype=torch.float64))

Int tensor([1, 2, 3], dtype=torch.int32)
Float tensor([1., 2., 3.], dtype=torch.float64)


In [33]:
# change datatype using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **Mathematical Operations**

In [47]:
m = torch.rand(2,2)
print(m)
# Addition
print("Add",m+2)
# Subtraction
print("Sub",m-2)
# Multiplication
print("Multiply",m*2)
# Division
print("Div",m/2)
# int division
print("Int Div",(m*100)//2)
# mod
print("Mod",(m*100)%2)
# power
print("Power",m**2)

tensor([[0.7267, 0.9486],
        [0.4388, 0.4589]])
Add tensor([[2.7267, 2.9486],
        [2.4388, 2.4589]])
Sub tensor([[-1.2733, -1.0514],
        [-1.5612, -1.5411]])
Multiply tensor([[1.4533, 1.8972],
        [0.8776, 0.9177]])
Div tensor([[0.3633, 0.4743],
        [0.2194, 0.2294]])
Int Div tensor([[36., 47.],
        [21., 22.]])
Mod tensor([[0.6670, 0.8607],
        [1.8819, 1.8858]])
Power tensor([[0.5280, 0.8999],
        [0.1926, 0.2106]])


In [45]:
# mathematical operations using two tensors
a = torch.rand(2,2)
b = torch.rand(2,2)
# Addition
print(a+b)
# Subtraction
print(a-b)
# ultiplication
print(a*b)
# Division
print(a/b)
# int division
print((a*100)//b)
# mod
print((a*100)%b)
# power
print(a**b)

tensor([[1.4074, 0.0912],
        [0.4420, 0.9901]])
tensor([[ 0.2709,  0.0152],
        [-0.1010, -0.4074]])
tensor([[0.4768, 0.0020],
        [0.0463, 0.2036]])
tensor([[1.4767, 1.3992],
        [0.6280, 0.4170]])
tensor([[147., 139.],
        [ 62.,  41.]])
tensor([[0.3825, 0.0351],
        [0.2162, 0.4876]])
tensor([[0.9051, 0.8945],
        [0.6186, 0.4225]])


# We can also use python functions like round,ceil,floor,clamp like torch.floor()


In [48]:
y = torch.randint(size=(2,3),low=0,high=9)
y

tensor([[4, 0, 3],
        [3, 4, 0]])

In [50]:
# sum -> gives the sum of all the values
print(torch.sum(y))
# sum via colums
print(torch.sum(y,dim=0))
# sum via rows
print(torch.sum(y,dim=1))

tensor(14)
tensor([7, 4, 3])
tensor([7, 7])


# Statistical Operations

In [54]:
z = torch.randint(size=(2,3),low=0,high=9,dtype=torch.float32)
# mean
print("Mean",torch.mean(z))
print("="*50)
# median
print("Mean",torch.median(z))
print("="*50)

# mode
print("Mode",torch.mode(z))
print("="*50)

# max
print("Max",torch.max(z))
print("="*50)

#min
print("Min",torch.min(z))
print("="*50)

# Standard Deviation
print("STD",torch.std(z))
print("="*50)

# Variance
print('Var',torch.var(z))
print("="*50)
# argmax and argmin
print("ArgMax",torch.argmax(z))
print("ArgMin",torch.argmin(z))
print("="*50)


Mean tensor(4.3333)
Mean tensor(4.)
Mode torch.return_types.mode(
values=tensor([2., 1.]),
indices=tensor([2, 0]))
Max tensor(8.)
Min tensor(1.)
STD tensor(2.5820)
Var tensor(6.6667)
ArgMax tensor(0)
ArgMin tensor(3)


# Matrix Operations

In [63]:
c = torch.rand(2,3)
d = torch.rand(3,2)

In [68]:
# matrix multiplication
print('Mat Mul',torch.matmul(c,d))
print("="*50)
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
# dot product
print("Dot Product",torch.dot(v1,v2))
print("="*50)
# transpose
print("Transpose",torch.transpose(c,0,1))

Mat Mul tensor([[1.7338, 0.7294],
        [1.4756, 0.7643]])
Dot Product tensor(11)
Transpose tensor([[0.5926, 0.9680],
        [0.7300, 0.1494],
        [0.9768, 0.9826]])


In [71]:
print(v1>v2)
print(v1<v2)
print(v1==v2)
print(v1<=v2)
print(v1>=v2)

tensor([False, False])
tensor([True, True])
tensor([False, False])
tensor([True, True])
tensor([False, False])


# Inplace Operations

# Why Inplace
- If we want to add v1 + v2 we need to store in another variable
- v3 = v1 + v2
- v3 takes another memory space
- to make it efficient we store the sum of v1 and v2 in one of these (v1 or v2)

- add _ to perform inplace operations

In [74]:
print("v1",v1)
print("v2",v2)
v1.add_(v2)
print(v1)

v1 tensor([ 7, 10])
v2 tensor([3, 4])
tensor([10, 14])


# Copying a Tensor

In [83]:
import torch

a = torch.rand(2, 3)
print("a:", a)  # Initial random 2x3 tensor

# Assuming 'b' should be the same reference
b = a  # b points to the same object as a
print("b (same as a):", b)

# Cloning 'a' to 'c' for a true shallow copy
c = a.clone()  # c is a new tensor with the same data
print("c (clone of a):", c)

# Modify 'a' and check effect on 'c'
a[0, 0] = 99  # Changing a should not affect c
print("Modified a:", a)
print("c after a change:", c)


a: tensor([[0.7539, 0.6718, 0.8547],
        [0.6662, 0.1022, 0.3406]])
b (same as a): tensor([[0.7539, 0.6718, 0.8547],
        [0.6662, 0.1022, 0.3406]])
c (clone of a): tensor([[0.7539, 0.6718, 0.8547],
        [0.6662, 0.1022, 0.3406]])
Modified a: tensor([[99.0000,  0.6718,  0.8547],
        [ 0.6662,  0.1022,  0.3406]])
c after a change: tensor([[0.7539, 0.6718, 0.8547],
        [0.6662, 0.1022, 0.3406]])


# Operations On GPU
- Until now we are not using GPU's

In [87]:
# Check GPU is available or not
torch.cuda.is_available()
# Store GPU
device = torch.device('cuda')
print(device)

cuda


In [88]:
# Creating a new tensor on GPU
torch.tensor([1,2],device=device)

tensor([1, 2], device='cuda:0')

In [89]:
# moving an existing tensor to GPU
q = torch.rand(2,2)
q.to(device)

tensor([[0.3004, 0.6601],
        [0.2266, 0.8444]], device='cuda:0')

# Reshape

In [90]:
a = torch.ones(4,4)
print(a)
a.reshape(2,2,2,2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [91]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
b = torch.rand(2,3,4)
print(b)
print("*"*50)
# permute
c = b.permute(2,0,1) # Here 2,0,1 are indices for 2,3,4
print(b.shape)
print(c.shape)

tensor([[[0.5838, 0.5919, 0.9227, 0.8773],
         [0.6719, 0.6709, 0.5859, 0.5352],
         [0.9730, 0.2216, 0.5942, 0.6693]],

        [[0.4632, 0.5951, 0.9750, 0.9116],
         [0.9228, 0.0453, 0.0866, 0.5617],
         [0.5345, 0.8589, 0.7819, 0.1666]]])
**************************************************
torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


Numpy and PyTorch

In [102]:
# Pytorch Tensor to Numpy array
tens = torch.tensor([1,2,3])
print(tens)
print(type(tens))
num = tens.numpy()
print(num)
print(type(num))

tensor([1, 2, 3])
<class 'torch.Tensor'>
[1 2 3]
<class 'numpy.ndarray'>


In [106]:
# Numpy to Pytorch
print(num)
print(type(num))
k = torch.from_numpy(num)
print(k)
print(type(k))

[1 2 3]
<class 'numpy.ndarray'>
tensor([1, 2, 3])
<class 'torch.Tensor'>
