In [1]:
import tensorflow as tf

# Tensorflow
- Tensorflow is a framework from google that is usefull to develop Machine Learning models and Deep learning models
### In Tensorflow: -
- Tensor -> Vector or Mulitidimentional Array
- Flow -> Represents the graph of operations
### Properties of Tensor: -
- A unique label (name)
- A dimention (shape)
- A data type (dtype)
### Types of Tensors: -
- tf.constant
- tf.Variable
- tf.Tensor
- tf.SparseTensor

## Constant Tensor

In [15]:
# tf.constsnt(value,dtype,name="")
import tensorflow as tf
c1 = tf.constant(10)
print("c1: ",c1)
c2 = tf.constant(10,tf.int16,name="My const")
print("c2: ",c2)
c3 = tf.constant("Hello Tensorflow")
print("c3: ",c3)

c1:  tf.Tensor(10, shape=(), dtype=int32)
c2:  tf.Tensor(10, shape=(), dtype=int16)
c3:  tf.Tensor(b'Hello Tensorflow', shape=(), dtype=string)


## Variable Tensor

In [16]:
# tf.Variable(value,dtype,name="")
v1 = tf.Variable(25)
print(v1)
# Change the value from 25 --> 45 using assign
v1.assign(45)
print(v1)
v1 = tf.Variable('Hello')
print(v1)
v1.assign('Hello Tensorflow')

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>


<tf.Variable 'UnreadVariable' shape=() dtype=string, numpy=b'Hello Tensorflow'>

### Creating Tensor with Arrays

In [21]:
arr1 = tf.constant([10,11,12,14])
print(arr1)
arr2 = tf.constant([[1,2,3,4],[4,3,2,1]])
print(arr2)
arr3 = tf.Variable([[[1,2,3,4],[4,3,2,1],[11,12,13,14]]])
print(arr3)

tf.Tensor([10 11 12 14], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
<tf.Variable 'Variable:0' shape=(1, 3, 4) dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4,  3,  2,  1],
        [11, 12, 13, 14]]])>


In [28]:
# We can check properties of an array us:-
print('arr3:',arr3.name)
print('arr2:',arr2.shape)
print('arr1',arr1.dtype)

arr3: Variable:0
arr2: (2, 4)
arr1 <dtype: 'int32'>


### Common Operations
- tf.add(a,b)
- tf.substract(a,b)
- tf.multiply(a,b)
- tf.div(a,b)
- tf.pow(a,b)
- tf.exp(a)
- tf.sqrt(a)
- tf.matmul(a,b) -> performs matrix multiplication on two matrices

In [32]:
# Program to add two numbers using tensorflow
a = tf.constant(100)
b = tf.constant(200)
c = tf.add(a,b)
print(c)

tf.Tensor(300, shape=(), dtype=int32)


# Keras
#####  Keras is used widely while creating models and Layers for ANN
### Layers in Keras
- Dense Layer
- Dropout Layer
- Flatten Layer
- Pooling Layer
- Convolution Layer
#### While Creating ANN we need to create the layers one by one and add them up sequentially so that the network is formed
- for this purpose we have Sequential Class in tensorflow.keras

In [39]:
# Dense Layer
from tensorflow.keras.models import Sequential
model = Sequential()

## Dense Layer
- It is widely used layer for creating Deep Neural Networks. 
- Each of the neurons of this layer(Dense) receives input from all the neurons of the previous layers.
- It performs dot product for all the inputs along with weights for obtaining output

In [42]:
from tensorflow.keras.layers import Dense
# Define a simple model using the Sequential Class
model = Sequential([
    Dense(32, activation='relu', input_shape=(784,)),  # First hidden layer
    Dense(10, activation='softmax')  # Output layer
])


## Dropout Layer
- Dropout layer will remove some of the node from functioning
- Input data may contain some unwanted data or duplicate data called noise
- Dropout layer removes noise thus preventing overfitting

In [43]:
from tensorflow.keras.layers import Dropout

# Define a simple model using the Sequential Class
model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),  # First hidden layer
    Dropout(0.2),  # 20% of the neurons will be dropped during training
    Dense(10, activation='softmax')  # Output layer
])


## Flatten Layer
- Flatten is used to convert a multi-dimensional input into a one-dimensional output.
- It is typically used after convolutional and pooling layers to feed the data into fully connected layers (Dense layers).
- The Flatten layer does not learn any parameters, it simply reshapes the data.

## Pooling Layer
- Pooling is used to reduce the spatial dimensions (width and height) of the input, while retaining the most important information.
- The two most common types of pooling are MaxPooling and AveragePooling:
- MaxPooling: Takes the maximum value from a defined window.
- AveragePooling: Takes the average value from the window.
- Pooling helps reduce computation and overfitting by reducing the dimensionality.

## Convolution Layer
- Convolution layers are the core building blocks of Convolutional Neural Networks (CNNs).
- They apply a set of learnable filters (kernels) to the input to create feature maps.
- Each filter scans across the input image and detects specific - patterns like edges, textures, or shapes.
- Convolution layers help preserve the spatial structure of data, unlike Dense layers which flatten the input.
- The parameters for the convolution layer include the number of filters, filter size, and stride.

In [45]:
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Conv2D
# Define a simple model using the Sequential Class
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),  # Convolution layer
    MaxPooling2D(pool_size=(2, 2)),  # Pooling layer
    Flatten(),  # Flatten the output of the previous layer to feed into the Dense layer
    Dense(10, activation='softmax')  # Output layer
])
